// let firstName:string="afshan";
// console.log(firstName);
// let last_name:string="feroz";
// console.log(last_name);
// let FullName:string="afshanferoz";
// console.log(FullName);
// let age:number= 27;
// console.log(age);
// let ismarried:boolean=true;
// console.log(ismarried);
// let qualification:string="B.com";
// console.log(qualification);
// let city:string="karachi";
// console.log(city);
// let country:string="pakistan";
// console.log(country);
// const dob:number=12011997;
// console.log(dob);
// const sibling:number=6;
// console.log(sibling);
// let hobby:string="reading";
// console.log(hobby);
// let profession:string="teaching";
// console.log(profession);
// let area:string='usmanabad';
// console.log(area);
// let town:string="lyari";
// console.log(town);
// let favoriteSubject:string="math";
// console.log(favoriteSubject);
// const religion:string="islam";
// console.log(religion);
var favouritegame = "cricket";
console.log(favouritegame);
favouritegame = "soccer";
console.log(favouritegame);
favouritegame = "volleyball";
console.log(favouritegame);
var favouriteWriter = "shakespear";
console.log(favouriteWriter);
var favouritescholer = "israrahmed";
console.log(favouritescholer);
var nickNAME = "aena";
console.log(nickNAME);
var height = 5.4;
console.log(height);
var favouritemovie = "tare zameen per";
console.log(favouritemovie);
var favouritesong = "who said";
console.log(favouritesong);
favouritesong = "flowers";
console.log(favouritesong);
var favouritecolour = "green";
var favouritepicnicplace = 'seaside';
var mothername = "ishrat";
console.log(favouritecolour);
console.log(favouritepicnicplace);
console.log(mothername);
var favouritequote = "do the best until you know better.then when you know better, do better ";
var favouriteweather = 'rain';
favouritequote = "success is not final failure is not fatal it is the courage to continue that count";
console.log(favouritequote);
console.log(favouriteweather);
console.log(favouritequote);
